[16:23] Ganesh Ukkusila

version: 0.0

os: linux

 

resources:

  - TargetService:

      Type: AWS::ECS::Service

      Properties:

        TaskDefinition: "arn:aws:ecs:us-east-2:823226410025:task-definition/service1:31"

        LoadBalancerInfo:

          ContainerName: "qt-container"

          ContainerPort: 8080
